export type CourseType = "recorded" | "free" | "live";
export type CourseCategory = "vastu" | "numerology" | "astrology";

export interface Course {
  slug: string;
  title: string;
  type: CourseType;
  category?: CourseCategory;
  teacher: string;
  tagline: string;
  description: string;
  price?: number;
  originalPrice?: number;
  buyUrl?: string;
  youtubeUrl?: string;
  badge?: string;
  image: string;
  features: string[];
  syllabus?: string[];
  duration?: string;
}

const CLASS_PLUS = "https://agafhe.courses.store";

const courseStore = (id: number | string, extra = "") => `${CLASS_PLUS}/courses/${id}${extra}`;

export const COURSES: Course[] = [
  // ===================== RECORDED =====================
  {
    slug: "graphology",
    title: "Graphology",
    type: "recorded",
    category: "numerology",
    teacher: "Arvindrun Vnjay",
    tagline: "Analyzes a signature and relates the findings to an individual's astrological profile.",
    description:
      "Graphology analyzes a signature and relates the findings to an individual's astrological profile to provide a more complete picture. Learn how handwriting and signature reveal personality, and how to correct a signature for better results.",
    price: 1000,
    originalPrice: 1999,
    buyUrl: courseStore(719266),
    image: "/images/courses/graphology.svg",
    features: ["Video lectures", "Video access", "Certificate"],
    syllabus: ["Introduction to Graphology", "Signature zones & energy", "Linking signature to birth chart", "Signature correction techniques", "Case studies & practice"],
    duration: "Validity: 4 months",
  },
  {
    slug: "devta-vastu",
    title: "Devta Energies in Vastu",
    type: "recorded",
    category: "vastu",
    teacher: "Arvindrun Vnjay",
    tagline: "Work with the energies of the 45 Vastu Devtas in the Vastu Purusha Mandala.",
    description:
      "Learn to work with the energies of the 45 Vastu Devtas (deities) in the Vastu Purusha Mandala for harmonizing spaces. A deep, rarely-taught Vastu module for serious practitioners.",
    price: 6000,
    originalPrice: 12999,
    buyUrl: courseStore(812792),
    image: "/images/courses/devta-vastu.svg",
    features: ["Video lectures", "Files included", "Video access"],
    syllabus: ["Vastu Purusha Mandala overview", "The 45 Devtas & their zones", "Devta energy activation", "Correction through Devta alignment", "Advanced case studies"],
    duration: "Validity: 9 months",
  },
  {
    slug: "9-star-lo-shu-grid",
    title: "9 Star ki LoshuGrid Numerology",
    type: "recorded",
    category: "numerology",
    teacher: "Arvindrun Vnjay",
    tagline: "Analyze personality, strengths, weaknesses, and life path using the ancient Chinese 3×3 magic square.",
    description:
      "Analyze personality, strengths, weaknesses, and life path from your birth using the ancient Chinese 3x3 magic square with 9 different Grids. A powerful predictive system loved by students worldwide.",
    price: 2500,
    originalPrice: 3999,
    buyUrl: courseStore(758789),
    image: "/images/courses/lo-shu-9.svg",
    features: ["Video lectures", "Files included", "Video access"],
    syllabus: ["Lo Shu Grid basics", "The 9 numbers & planetary links", "Missing & repeated numbers", "Predictions from the grid", "Remedies & case studies"],
    duration: "Validity: 9 months",
  },
  {
    slug: "advanced-predictive-numerology",
    title: "Advanced Predictive Numerology",
    type: "recorded",
    category: "numerology",
    teacher: "Arvindrun Vnjay",
    tagline: "Most awaited & popular Advanced Predictive Numerology course with Predictive Powers.",
    description:
      "Most awaited & popular Advanced Predictive Numerology course is here with Predictive Powers. Move beyond basics and learn professional-level prediction techniques used in real consultations.",
    price: 15000,
    originalPrice: 24999,
    badge: "Most Popular",
    buyUrl: courseStore(741145),
    image: "/images/courses/advanced-numerology.svg",
    features: ["Video lectures", "Files included", "Video access", "Certificate"],
    syllabus: ["Foundation revision", "Predictive techniques (advanced)", "Event timing by numbers", "Compatibility & name corrections", "Live case studies"],
    duration: "Validity: 12 months",
  },
  {
    slug: "predictive-name-numerology",
    title: "Predictive Name Numerology",
    type: "recorded",
    category: "numerology",
    teacher: "Arvindrun Vnjay",
    tagline: "Most awaited Predictive Name Numerology Course with many Tips & Tricks to Predict.",
    description:
      "Most awaited & popular Predictive Name Numerology Course with many Tips & Tricks to Predict. Master the art of reading any name like an open book and predicting outcomes through name vibrations.",
    price: 15000,
    originalPrice: 24999,
    buyUrl: courseStore(668404),
    image: "/images/courses/predictive-name.svg",
    features: ["Video lectures", "Files included", "Video access", "Certificate"],
    syllabus: ["Alphabet & vibration science", "Name reading techniques", "Predicting career, marriage, wealth", "Name correction mastery", "Case studies"],
    duration: "Validity: 12 months",
  },
  {
    slug: "medical-vastu",
    title: "Medical Vastu",
    type: "recorded",
    category: "vastu",
    teacher: "Arvindrun Vnjay",
    tagline: "Comprehensive course covering the basics of Vastu Shastra applied in a medical context.",
    description:
      "This comprehensive course covers the basics of Vastu Shastra, focusing on its application in a medical context — how spaces create health imbalances and how to correct them.",
    price: 3000,
    originalPrice: 6999,
    buyUrl: courseStore(675960),
    image: "/images/courses/medical-vastu.svg",
    features: ["Video lectures", "Files included", "Video access"],
    syllabus: ["Vastu & health correlation", "Zone mapping for body parts", "Hospitals & clinics Vastu", "Home health corrections", "Case studies"],
    duration: "Validity: 9 months",
  },
  {
    slug: "vastu-fundamentals-16-zones",
    title: "Vastu Fundamentals: Understanding 16 Zones",
    type: "recorded",
    category: "vastu",
    teacher: "Arvindrun Vnjay",
    tagline: "Foundational principles of Vastu focusing on the 16 zones with Bar chart, Degree & Google Earth.",
    description:
      "This basic course introduces the foundational principles of Vastu Shastra, focusing on the 16 zones and their significance with Bar chart, Degree & Google Earth. Perfect starting point for beginners.",
    price: 1000,
    originalPrice: 2999,
    buyUrl: courseStore(677148),
    image: "/images/courses/vastu-fundamentals.svg",
    features: ["Video lectures", "Files included", "Video access"],
    syllabus: ["Introduction to 16 zones", "Directions & degrees", "Zone-wise remedies", "Reading floor plans", "Google Earth practice"],
    duration: "Validity: 8 months",
  },
  {
    slug: "medical-astrology",
    title: "Medical Astrology",
    type: "recorded",
    category: "astrology",
    teacher: "Arvindrun Vnjay",
    tagline: "Unlock the Secrets of Predicting Health Issues with Astrology.",
    description:
      "Are you ready to predict diseases using the power of astrology? This course teaches how health issues are seen in a birth chart — from houses, signs, and planetary combinations — with remedial guidance.",
    price: 3000,
    originalPrice: 6999,
    badge: "Featured",
    buyUrl: courseStore(628940),
    image: "/images/courses/medical-astrology.svg",
    features: ["Video lectures", "Files included", "Video access"],
    syllabus: ["Astrology of the human body", "12 houses & health", "Disease-indicating combinations", "Predicting health events", "Remedies & case studies"],
    duration: "Validity: 12 months",
  },
  {
    slug: "alphabets",
    title: "Alphabets",
    type: "recorded",
    category: "numerology",
    teacher: "Arvindrun Vnjay",
    tagline: "Name Numerology A–Z course — decode the hidden meaning behind every alphabet.",
    description:
      "Name Numerology A–Z Course. Decode the hidden meaning behind every alphabet — A to Z. Curious how names affect destiny? This is where it all begins.",
    price: 1500,
    originalPrice: 2999,
    buyUrl: courseStore(547379),
    image: "/images/courses/alphabets.svg",
    features: ["Video lectures", "Video access"],
    syllabus: ["Alphabet vibration values", "Chaldean & Pythagorean tables", "Letter-by-letter analysis", "Name reading practice"],
    duration: "Validity: 6 months",
  },
  {
    slug: "lo-shu-numerology",
    title: "Lo Shu Numerology",
    type: "recorded",
    category: "numerology",
    teacher: "Arvindrun Vnjay",
    tagline: "Unlock the secrets of the Lo Shu Grid with powerful predictive techniques.",
    description:
      "Unlock the secrets of the Lo Shu Grid! This course introduces you to the Lo Shu Numerology system with powerful predictive techniques for personality, career, and relationships.",
    price: 2500,
    originalPrice: 4999,
    badge: "Featured",
    buyUrl: courseStore(520879),
    image: "/images/courses/lo-shu.svg",
    features: ["Video lectures", "Video access"],
    syllabus: ["Lo Shu Grid introduction", "Number placements & meanings", "Predictions from grid patterns", "Remedies"],
    duration: "Validity: 10 months",
  },
  {
    slug: "know-the-number-1-9",
    title: "Know the Number 1-9",
    type: "recorded",
    category: "numerology",
    teacher: "Arvindrun Vnjay",
    tagline: "Understand each number deeply — traits, influences, and characteristics of every number 1 to 9.",
    description:
      "Are you a numerology enthusiast looking to understand each number deeply? In this course, we dive into the detailed traits, influences, and characteristics of each number from 1 to 9.",
    price: 1500,
    originalPrice: 2999,
    buyUrl: courseStore(508414),
    image: "/images/courses/numbers.svg",
    features: ["Video lectures", "Video access"],
    syllabus: ["Number 1–3 deep dive", "Number 4–6 deep dive", "Number 7–9 deep dive", "Planetary connections"],
    duration: "Validity: 6 months",
  },
  {
    slug: "vedic-numerology",
    title: "Vedic Numerology",
    type: "recorded",
    category: "numerology",
    teacher: "Arvindrun Vnjay",
    tagline: "Make accurate predictions based on the numbers in your Date of Birth (DOB).",
    description:
      "Are you fascinated by the power of numbers in Vedic Numerology? This course teaches you how to make accurate predictions based on the numbers in your Date of Birth (DOB).",
    price: 2500,
    originalPrice: 4999,
    badge: "Featured",
    buyUrl: courseStore(506472),
    image: "/images/courses/vedic-numerology.svg",
    features: ["Video lectures", "Video access"],
    syllabus: ["Vedic number system", "DOB & life path", "Predictions from birth numbers", "Remedies"],
    duration: "Validity: 10 months",
  },
  {
    slug: "basic-astrology",
    title: "Basic Astrology",
    type: "recorded",
    category: "astrology",
    teacher: "Arvindrun Vnjay",
    tagline: "Build a strong foundation in Astrology with this in-depth beginner course.",
    description:
      "Learn in-depth Basic Astrology — after doing this course you can build a strong base in Astrology. Ideal for absolute beginners who want to read charts with confidence.",
    price: 4000,
    originalPrice: 8999,
    badge: "Featured",
    buyUrl: CLASS_PLUS,
    image: "/images/courses/basic-astrology.svg",
    features: ["Video lectures", "Video access", "Certificate"],
    syllabus: ["Zodiac signs & elements", "Planets & their meanings", "Houses & significations", "Reading a birth chart", "Dasha basics"],
    duration: "Validity: 14 months",
  },
  {
    slug: "marriage-astrology",
    title: "Marriage Astrology (विवाह ज्योतिष)",
    type: "recorded",
    category: "astrology",
    teacher: "Arvindrun Vnjay",
    tagline: "Analyze marital compatibility, predict marriage timing, and identify solutions.",
    description:
      "Analyze marital compatibility, predict marriage timing, and identify solutions for marital issues. One of the most in-demand astrology skills — taught with real charts.",
    price: 3000,
    originalPrice: 6999,
    badge: "Featured",
    buyUrl: courseStore(505636),
    image: "/images/courses/marriage.svg",
    features: ["Video lectures", "Files included", "Video access"],
    syllabus: ["Marriage houses & yogas", "Compatibility (Ashtakoota)", "Timing of marriage", "Marital problem remedies"],
    duration: "Validity: 10 months",
  },
  {
    slug: "progeny-astrology",
    title: "Progeny Astrology (संतान ज्योतिष)",
    type: "recorded",
    category: "astrology",
    teacher: "Arvindrun Vnjay",
    tagline: "Determine the likelihood of having children, challenges, and timing of childbirth.",
    description:
      "Determine the likelihood of having children, potential challenges, and the timing of childbirth from the birth chart. A specialized and sensitive branch of astrology.",
    price: 3000,
    originalPrice: 6999,
    badge: "Featured",
    buyUrl: courseStore(505625),
    image: "/images/courses/progeny.svg",
    features: ["Video lectures", "Files included", "Video access"],
    syllabus: ["5th house & progeny", "Child-delivery yogas", "Obstacle combinations", "Timing of childbirth", "Remedies"],
    duration: "Validity: 12 months",
  },
  {
    slug: "profession-career-astrology",
    title: "Profession & Career Astrology",
    type: "recorded",
    category: "astrology",
    teacher: "Arvindrun Vnjay",
    tagline: "Career guidance through the birth chart — strengths & timing of opportunity.",
    description:
      "Analyzes a person's birth chart to offer guidance on career choices, strengths & timing of opportunity. Learn how to guide clients (or yourself) to the right profession.",
    price: 3000,
    originalPrice: 6999,
    badge: "Featured",
    buyUrl: courseStore(536605),
    image: "/images/courses/career.svg",
    features: ["Video lectures", "Files included", "Video access"],
    syllabus: ["10th house & career", "Significators of profession", "Career change timing", "Business vs job analysis", "Case studies"],
    duration: "Validity: 12 months",
  },
  {
    slug: "bhrigu-chakra-padhati",
    title: "Bhrigu Chakra Padhati Basic",
    type: "recorded",
    category: "astrology",
    teacher: "Arvindrun Vnjay",
    tagline: "Ancient Vedic method to predict life events, reveal karma, and guide destiny.",
    description:
      "Bhrigu Chakra Padhiti is an ancient Vedic astrology method to predict life events, reveal karma, and guide destiny. A rarely taught, powerful predictive system.",
    price: 1500,
    originalPrice: 2999,
    badge: "Featured",
    buyUrl: courseStore(653075),
    image: "/images/courses/bhrigu.svg",
    features: ["Video lectures", "Files included", "Video access"],
    syllabus: ["Bhrigu Chakra fundamentals", "Sapthamsa & Navamsa usage", "Event prediction techniques", "Karma reading", "Practice charts"],
    duration: "Validity: 9 months",
  },
  {
    slug: "pythagorean-numerology",
    title: "Pythagorean Numerology",
    type: "recorded",
    category: "numerology",
    teacher: "Arvindrun Vnjay",
    tagline: "The numerology system that connects numbers to personality, destiny, and purpose.",
    description:
      "It is a type of numerology system that connects numbers to personality, destiny, and purpose. Learn the Western system that complements Vedic numerology beautifully.",
    price: 2500,
    originalPrice: 3999,
    buyUrl: courseStore(504051),
    image: "/images/courses/pythagorean.svg",
    features: ["Video lectures", "Video access"],
    syllabus: ["Pythagorean table", "Life path & destiny numbers", "Expression & soul urge", "Western vs Vedic comparison"],
    duration: "Validity: 9 months",
  },
  {
    slug: "prediction-from-currency-notes",
    title: "Predict & Improve Your Financial Condition By Currency Note",
    type: "recorded",
    category: "numerology",
    teacher: "Arvindrun Vnjay",
    tagline: "Certain serial number combinations hold special meaning or can influence wealth & fortune.",
    description:
      "Certain serial number combinations hold special meaning or can influence wealth & fortune. A unique and fun predictive technique that is also a great client magnet.",
    price: 999,
    originalPrice: 1999,
    badge: "Featured",
    buyUrl: courseStore(503673),
    image: "/images/courses/currency.svg",
    features: ["Video lectures", "Video access"],
    syllabus: ["Serial number analysis", "Combinations & meanings", "Wealth predictions", "Practical usage"],
    duration: "Validity: 3 months",
  },
  {
    slug: "wealth-prosperity-foreign-astrology",
    title: "Wealth Property Foreign Astrology",
    type: "recorded",
    category: "astrology",
    teacher: "Arvindrun Vnjay",
    tagline: "Time events & understand issues related to Wealth, Property & Foreign settlement & Travel.",
    description:
      "You can time events & also understand the issues related to Wealth, Property & Foreign settlement & Travel. One of the most valuable specializations for modern astrology practice.",
    price: 3000,
    originalPrice: 6999,
    badge: "Featured",
    buyUrl: courseStore(524835),
    image: "/images/courses/wealth.svg",
    features: ["Video lectures", "Files included", "Video access"],
    syllabus: ["Wealth houses & yogas", "Property indicators", "Foreign settlement combinations", "Travel timing", "Case studies"],
    duration: "Validity: 12 months",
  },
  {
    slug: "complete-vastu-course",
    title: "Complete Vastu Course from Basic to Advance",
    type: "recorded",
    category: "vastu",
    teacher: "Arvindrun Vnjay",
    tagline: "The full Vastu Shastra journey — from absolute basics to professional-level practice.",
    description:
      "The most comprehensive Vastu training we offer. From the foundations of direction science to professional-level zone correction, this course takes you from a complete beginner to a confident Vastu consultant.",
    price: 15000,
    originalPrice: 24999,
    badge: "Full Course",
    buyUrl: `${CLASS_PLUS}?search=vastu`,
    image: "/images/courses/complete-vastu.svg",
    features: ["Video lectures", "Files included", "Video access", "Certificate"],
    syllabus: ["Vastu foundations", "16 zones in depth", "Devta energies", "Toilet & kitchen corrections", "Business & home Vastu", "Professional practice setup"],
    duration: "Validity: 12 months",
  },

  // ===================== RECORDED (New) =====================
  {
    slug: "medical-vastu-numerology",
    title: "Medical & Vastu Numerology",
    type: "recorded",
    category: "numerology",
    teacher: "Arvindrun Vnjay",
    tagline: "Combine numerology with vastu and health insights to predict and correct well-being.",
    description:
      "Learn how numerology connects with vastu and health. This course teaches you to analyze numbers for health predictions and use vastu-numerology combinations for effective remedies.",
    price: 2000,
    originalPrice: 3999,
    buyUrl: CLASS_PLUS,
    image: "/images/courses/medical-vastu.svg",
    features: ["Video lectures", "Video access", "Certificate"],
    syllabus: ["Numbers & health mapping", "Medical numerology indicators", "Vastu & number alignment", "Remedies & case studies"],
    duration: "Validity: 9 months",
  },
  {
    slug: "surya-paddhati",
    title: "Surya Paddhati — Sun Progression Method",
    type: "recorded",
    category: "astrology",
    teacher: "Arvindrun Vnjay",
    tagline: "Predict events and time life phases using the powerful Sun-based progression system.",
    description:
      "Surya Paddhati is a Sun Progression Method that gives remarkable timing of events. Learn this precise predictive technique for accurate event timing in consultations.",
    price: 1500,
    originalPrice: 3999,
    buyUrl: CLASS_PLUS,
    image: "/images/courses/basic-astrology.svg",
    features: ["Video lectures", "Video access", "Certificate"],
    syllabus: ["Surya Paddhati fundamentals", "Sun progression calculations", "Event timing techniques", "Practice charts"],
    duration: "Validity: 9 months",
  },

  // ===================== FREE =====================
  {
    slug: "learn-jagannath-hora-software",
    title: "Learn Jagannath Hora Software",
    type: "free",
    teacher: "Arvindrun Vnjay",
    tagline: "Learn to use Jagannatha Hora Astrology software in detail with few secrets of astrology.",
    description:
      "Learn to use Jagannatha Hora Astrology software in detail with few secrets of Astrology. Video language: Hindi. The perfect free starting point to practice charts.",
    youtubeUrl: "https://www.youtube.com/playlist?list=PLn1-1oorZ6H5VtgFrOOcBtIm7cMImJil5",
    image: "/images/courses/free-hora.svg",
    features: ["Free YouTube playlist", "Hindi language", "Beginner friendly"],
  },
  {
    slug: "marriage-astrology-free",
    title: "Marriage Astrology (Free Series)",
    type: "free",
    teacher: "Arvindrun Vnjay",
    tagline: "Know all about marriage — good or bad marriage, timing & no-marriage conditions.",
    description:
      "In this course you will get to know all about marriage like good or bad marriage, how to time marriage & no marriage etc. A complete free series on marriage astrology.",
    youtubeUrl: "https://www.youtube.com/playlist?list=PLn1-1oorZ6H5jNXRW-0IqFgXQ7w4L2p2m",
    image: "/images/courses/free-marriage.svg",
    features: ["Free YouTube playlist", "Hindi language", "Real chart examples"],
  },
  {
    slug: "learn-32-vastu-entrances",
    title: "Learn 32 Vastu Entrances",
    type: "free",
    teacher: "Arvindrun Vnjay",
    tagline: "Know all 32 Vastu entrances results with symptoms & remedies.",
    description:
      "In this course you will get to know all 32 vastu entrances results with symptoms & remedies. A unique free series that gives deep Vastu knowledge.",
    youtubeUrl: "https://www.youtube.com/playlist?list=PLn1-1oorZ6H4B2iUtG2ZIBQPY-O3ETFFi",
    image: "/images/courses/free-vastu-entrances.svg",
    features: ["Free YouTube playlist", "Hindi language", "32 entrances explained"],
  },
  {
    slug: "vastu-symbolic-remedies",
    title: "Vastu Symbolic Remedies For All Directions",
    type: "free",
    teacher: "Arvindrun Vnjay",
    tagline: "Learn all Vastu symbolic remedies for all directions.",
    description:
      "In this course you will get to know all vastu symbolic remedies for all directions. Simple, practical remedies you can apply immediately.",
    youtubeUrl: "https://www.youtube.com/playlist?list=PLn1-1oorZ6H57QPb2Lh7iV0ajI4Pu8OsK",
    image: "/images/courses/free-remedies.svg",
    features: ["Free YouTube playlist", "Hindi language", "Direction-wise remedies"],
  },

  // ===================== LIVE =====================
  {
    slug: "predictive-numerology-course",
    title: "Predictive Numerology Course",
    type: "live",
    teacher: "Arvindrun Vnjay",
    tagline: "Master the art of professional prediction through live interactive classes.",
    description:
      "The flagship live course where you learn to predict like a professional numerologist. Live classes with real-time Q&A, recorded backups, and community support. Covers everything from number foundations to advanced predictive techniques used in paid consultations.",
    image: "/images/courses/live-predictive.svg",
    features: ["Live interactive classes", "Real-time Q&A with Arvindrun Vnjay", "Recorded for later", "Community support", "Certificate on completion"],
    duration: "8–10 weeks · Weekend batches",
    syllabus: [
      "Number foundations & planetary links",
      "Life path, destiny & personal year numbers",
      "Predictive techniques from DOB & name",
      "Mobile number & vehicle number analysis",
      "Event timing predictions",
      "Live practice on real charts",
      "Setting up your own practice",
    ],
  },
  {
    slug: "complete-basic-to-advanced-vastu-course",
    title: "Complete Basic To Advanced Vastu Course",
    type: "live",
    teacher: "Arvindrun Vnjay",
    tagline: "From Vastu fundamentals to professional-level correction techniques — live.",
    description:
      "A structured live journey through Vastu Shastra: directions, 16 zones, the Vastu Purusha Mandala, and practical correction techniques. You'll learn to read floor plans, use a compass, and deliver remedies clients can actually implement.",
    image: "/images/courses/live-vastu.svg",
    features: ["Live interactive classes", "Floor-plan practice", "Compass & Google Earth training", "Recorded for later", "Certificate on completion"],
    duration: "10–12 weeks · Weekend batches",
    syllabus: [
      "Vastu foundations & directions",
      "16 zones with degree accuracy",
      "Vastu Purusha Mandala & 45 Devtas",
      "Toilet, kitchen, bedroom corrections",
      "Business & shop Vastu",
      "Practical remedy application",
      "Professional consulting setup",
    ],
  },
  {
    slug: "predictive-name-numerology-course",
    title: "Predictive Name Numerology Course",
    type: "live",
    teacher: "Arvindrun Vnjay",
    tagline: "Learn name vibration & graphology to predict and design names professionally.",
    description:
      "Live training in the most in-demand numerological skill — name analysis. Learn how every letter vibrates, how to read any name, how to correct names for clients, and how to design newborn & business names professionally.",
    image: "/images/courses/live-name.svg",
    features: ["Live interactive classes", "Name correction workshops", "Graphology basics", "Recorded for later", "Certificate on completion"],
    duration: "6–8 weeks · Weekend batches",
    syllabus: [
      "Alphabet vibration science",
      "Chaldean & Pythagorean systems",
      "Reading names — career, marriage, wealth",
      "Name correction for clients",
      "Newborn & business name designing",
      "Graphology & signature correction",
    ],
  },
  {
    slug: "prashna-kundali",
    title: "Prashna Kundali",
    type: "live",
    teacher: "Arvindrun Vnjay",
    tagline: "The ancient art of answering questions through the moment of asking.",
    description:
      "Prashna (horary) astrology answers questions through the chart of the moment the question is asked — no birth details needed. Learn this powerful technique live, with abundant practice and authentic traditional methods.",
    image: "/images/courses/prashna.svg",
    features: ["Live interactive classes", "Traditional technique focus", "Real practice charts", "Recorded for later", "Certificate on completion"],
    duration: "6 weeks · Weekend batches",
    syllabus: [
      "Prashna fundamentals",
      "Casting the question chart",
      "Planet & house responses",
      "Timing the answer",
      "Yes/No & detail prediction",
      "Practice sessions",
    ],
  },
];

export const RECORDED_COURSES = COURSES.filter((c) => c.type === "recorded");
export const FREE_COURSES = COURSES.filter((c) => c.type === "free");
export const LIVE_COURSES = COURSES.filter((c) => c.type === "live");

export function getCourse(slug: string) {
  return COURSES.find((c) => c.slug === slug);
}
