export type CourseType = "recorded" | "free" | "live";
export type CourseCategory = "vastu" | "numerology" | "astrology";

export interface Course {
  slug: string;
  title: string;
  type: CourseType;
  category?: CourseCategory;
  teacher: string;
  tagline: string;
  description: string;
  price?: number;
  originalPrice?: number;
  priceNote?: string;
  buyUrl?: string;
  payUrl?: string;
  youtubeUrl?: string;
  badge?: string;
  image: string;
  features: string[];
  syllabus?: string[];
  duration?: string;
  about?: string;
  whyJoin?: string[];
  perks?: string[];
  startsFrom?: string;
  bullets?: string[];
  learnLink?: string;
  beginnerNote?: string;
  language?: string;
  priceSuffix?: string;
  liveSessionTitle?: string;
  liveSessionBody?: string;
}

const CLASS_PLUS = "https://agafhe.courses.store";

const courseStore = (id: number | string, extra = "") => `${CLASS_PLUS}/courses/${id}${extra}`;

export const COURSES: Course[] = [
  // ===================== RECORDED =====================
  {
    slug: "graphology",
    title: "Graphology",
    type: "recorded",
    category: "numerology",
    teacher: "Arvindrun Vnjay",
    tagline: "Analyzes a signature and relates the findings to an individual's astrological profile.",
    description:
      "Graphology analyzes a signature and relates the findings to an individual's astrological profile to provide a more complete picture.",
    price: 1000,
    originalPrice: 1999,
    buyUrl: courseStore(719266),
    image: "/images/courses/graphology.png",
    features: ["Video lectures", "Video access", "Certificate"],
    syllabus: ["Introduction to Graphology", "Signature zones & energy", "Linking signature to birth chart", "Signature correction techniques", "Case studies & practice"],
    duration: "Validity: 4 months",
  },
  {
    slug: "devta-vastu",
    title: "Devta Vastu",
    type: "recorded",
    category: "vastu",
    teacher: "Arvindrun Vnjay",
    tagline: "Work with the energies of the 45 Vastu Devtas in the Vastu Purusha Mandala.",
    description:
      "Learn to work with the energies of the 45 Vastu Devtas (deities) in the Vastu Purusha Mandala for harmonizing spaces.",
    price: 6000,
    originalPrice: 12999,
    buyUrl: courseStore(812792),
    image: "/images/courses/devta-vastu.png",
    features: ["Video lectures", "Files included", "Video access"],
    syllabus: ["Vastu Purusha Mandala overview", "The 45 Devtas & their zones", "Devta energy activation", "Correction through Devta alignment", "Advanced case studies"],
    duration: "Validity: 9 months",
  },
  {
    slug: "9-star-lo-shu-grid",
    title: "9 star Lo Shu Grid Numerology",
    type: "recorded",
    category: "numerology",
    teacher: "Arvindrun Vnjay",
    tagline: "Analyze personality, strengths, weaknesses, and life path using the ancient Chinese 3×3 magic square.",
    description:
      "Analyze personality, strengths, weaknesses, and life path from your birth using the ancient Chinese 3x3 magic square with 9 diffrent Grids",
    price: 2500,
    originalPrice: 3999,
    buyUrl: courseStore(758789),
    image: "/images/courses/9-star-lo-shu-grid.png",
    features: ["Video lectures", "Files included", "Video access"],
    syllabus: ["Lo Shu Grid basics", "The 9 numbers & planetary links", "Missing & repeated numbers", "Predictions from the grid", "Remedies & case studies"],
    duration: "Validity: 9 months",
  },
  {
    slug: "advanced-predictive-numerology",
    title: "Advanced Predictive Numerology",
    type: "recorded",
    category: "numerology",
    teacher: "Arvindrun Vnjay",
    tagline: "Most awaited & popular Advanced Predictive Numerology course with Predictive Powers.",
    description:
      "Most Awaited & Popular Advanced Predictive Numerology course is here with Predictive Powers.",
    price: 15000,
    originalPrice: 24999,
    badge: "Most Popular",
    buyUrl: courseStore(741145),
    image: "/images/courses/advanced-predictive-numerology.png",
    features: ["Video lectures", "Files included", "Video access", "Certificate"],
    syllabus: ["Foundation revision", "Predictive techniques (advanced)", "Event timing by numbers", "Compatibility & name corrections", "Live case studies"],
    duration: "Validity: 12 months",
  },
  {
    slug: "predictive-name-numerology",
    title: "Predictive Name Numerology",
    type: "recorded",
    category: "numerology",
    teacher: "Arvindrun Vnjay",
    tagline: "Most awaited Predictive Name Numerology Course with many Tips & Tricks to Predict.",
    description:
      "Most Awaited & Popular Predictive Name Numerology Course with many Tips & Tricks to Predict.",
    price: 15000,
    originalPrice: 24999,
    buyUrl: courseStore(668404),
    image: "/images/courses/predictive-name-numerology.png",
    features: ["Video lectures", "Files included", "Video access", "Certificate"],
    syllabus: ["Alphabet & vibration science", "Name reading techniques", "Predicting career, marriage, wealth", "Name correction mastery", "Case studies"],
    duration: "Validity: 12 months",
  },
  {
    slug: "medical-vastu",
    title: "Medical Vastu",
    type: "recorded",
    category: "vastu",
    teacher: "Arvindrun Vnjay",
    tagline: "Comprehensive course covering the basics of Vastu Shastra applied in a medical context.",
    description:
      "This comprehensive course covers the basics of Vastu Shastra, focusing on its application in medical Context.",
    price: 3000,
    originalPrice: 6999,
    buyUrl: courseStore(675960),
    image: "/images/courses/medical-vastu.png",
    features: ["Video lectures", "Files included", "Video access"],
    syllabus: ["Vastu & health correlation", "Zone mapping for body parts", "Hospitals & clinics Vastu", "Home health corrections", "Case studies"],
    duration: "Validity: 9 months",
  },
  {
    slug: "vastu-fundamentals-16-zones",
    title: "Vastu Fundamentals: Understanding 16 Zones",
    type: "recorded",
    category: "vastu",
    teacher: "Arvindrun Vnjay",
    tagline: "Foundational principles of Vastu focusing on the 16 zones with Bar chart, Degree & Google Earth.",
    description:
      "This basic course introduces the foundational principles of Vastu Shastra, focusing on the 16 zones and their significance with Bar chart, Degree & Google Earth",
    price: 1000,
    originalPrice: 2999,
    buyUrl: courseStore(677148),
    image: "/images/courses/vastu-fundamentals-16-zones.png",
    features: ["Video lectures", "Files included", "Video access"],
    syllabus: ["Introduction to 16 zones", "Directions & degrees", "Zone-wise remedies", "Reading floor plans", "Google Earth practice"],
    duration: "Validity: 8 months",
  },
  {
    slug: "medical-astrology",
    title: "Medical Astrology",
    type: "recorded",
    category: "astrology",
    teacher: "Arvindrun Vnjay",
    tagline: "Unlock the Secrets of Predicting Health Issues with Astrology.",
    description:
      "Unlock the Secrets of Predicting Health Issues with Astrology Are you ready to predict diseases using the power of astrology?",
    price: 3000,
    originalPrice: 6999,
    badge: "Featured",
    buyUrl: courseStore(628940),
    image: "/images/courses/medical-astrology.png",
    features: ["Video lectures", "Files included", "Video access"],
    syllabus: ["Astrology of the human body", "12 houses & health", "Disease-indicating combinations", "Predicting health events", "Remedies & case studies"],
    duration: "Validity: 12 months",
  },
  {
    slug: "alphabets",
    title: "Alphabets",
    type: "recorded",
    category: "numerology",
    teacher: "Arvindrun Vnjay",
    tagline: "Name Numerology A–Z course — decode the hidden meaning behind every alphabet.",
    description:
      "Name Numerology A–Z Course Decode the Hidden Meaning Behind Every Alphabet – A to Z Curious how names affect destiny?",
    price: 1500,
    originalPrice: 2999,
    buyUrl: courseStore(547379),
    image: "/images/courses/alphabets.png",
    features: ["Video lectures", "Video access"],
    syllabus: ["Alphabet vibration values", "Chaldean & Pythagorean tables", "Letter-by-letter analysis", "Name reading practice"],
    duration: "Validity: 6 months",
  },
  {
    slug: "lo-shu-numerology",
    title: "Lo Shu Numerology",
    type: "recorded",
    category: "numerology",
    teacher: "Arvindrun Vnjay",
    tagline: "Unlock the secrets of the Lo Shu Grid with powerful predictive techniques.",
    description:
      "Unlock the secrets of the Lo Shu Grid! This course introduces you to the Lo Shu Numerology system with powerful predictive techniques.",
    price: 2500,
    originalPrice: 4999,
    badge: "Featured",
    buyUrl: courseStore(520879),
    image: "/images/courses/lo-shu-numerology.png",
    features: ["Video lectures", "Video access"],
    syllabus: ["Lo Shu Grid introduction", "Number placements & meanings", "Predictions from grid patterns", "Remedies"],
    duration: "Validity: 10 months",
  },
  {
    slug: "know-the-number-1-9",
    title: "Know the Number 1-9",
    type: "recorded",
    category: "numerology",
    teacher: "Arvindrun Vnjay",
    tagline: "Understand each number deeply — traits, influences, and characteristics of every number 1 to 9.",
    description:
      "Are you a numerology enthusiast looking to understand each number deeply? In this course, we dive into the detailed traits, influences, and characteristics of each number from 1 to 9.",
    price: 1500,
    originalPrice: 2999,
    buyUrl: courseStore(508414),
    image: "/images/courses/know-the-number-1-9.png",
    features: ["Video lectures", "Video access"],
    syllabus: ["Number 1–3 deep dive", "Number 4–6 deep dive", "Number 7–9 deep dive", "Planetary connections"],
    duration: "Validity: 6 months",
  },
  {
    slug: "vedic-numerology",
    title: "Vedic Numerology",
    type: "recorded",
    category: "numerology",
    teacher: "Arvindrun Vnjay",
    tagline: "Make accurate predictions based on the numbers in your Date of Birth (DOB).",
    description:
      "Are you fascinated by the power of numbers in Vedic Numerology? This course teaches you how to make accurate predictions based on the numbers in your Date of Birth (DOB).",
    price: 2500,
    originalPrice: 4999,
    badge: "Featured",
    buyUrl: courseStore(506472),
    image: "/images/courses/vedic-numerology.png",
    features: ["Video lectures", "Video access"],
    syllabus: ["Vedic number system", "DOB & life path", "Predictions from birth numbers", "Remedies"],
    duration: "Validity: 10 months",
  },
  {
    slug: "basic-astrology",
    title: "Basic Astrology",
    type: "recorded",
    category: "astrology",
    teacher: "Arvindrun Vnjay",
    tagline: "Build a strong foundation in Astrology with this in-depth beginner course.",
    description:
      "Learn In depth Basic Astrology after doing this course you can build a strong base in Astrology.",
    price: 4000,
    originalPrice: 8999,
    badge: "Featured",
    buyUrl: CLASS_PLUS,
    image: "/images/courses/basic-astrology.png",
    features: ["Video lectures", "Video access", "Certificate"],
    syllabus: ["Zodiac signs & elements", "Planets & their meanings", "Houses & significations", "Reading a birth chart", "Dasha basics"],
    duration: "Validity: 14 months",
  },
  {
    slug: "marriage-astrology",
    title: "Marriage Astrology (विवाह ज्योतिष)",
    type: "recorded",
    category: "astrology",
    teacher: "Arvindrun Vnjay",
    tagline: "Analyze marital compatibility, predict marriage timing, and identify solutions.",
    description:
      "Analyze marital compatibility, predict marriage timing, and identify solutions for marital issues",
    price: 3000,
    originalPrice: 6999,
    badge: "Featured",
    buyUrl: courseStore(505636),
    image: "/images/courses/marriage-astrology.png",
    features: ["Video lectures", "Files included", "Video access"],
    syllabus: ["Marriage houses & yogas", "Compatibility (Ashtakoota)", "Timing of marriage", "Marital problem remedies"],
    duration: "Validity: 10 months",
  },
  {
    slug: "progeny-astrology",
    title: "Progeny Astrology (संतान ज्योतिष)",
    type: "recorded",
    category: "astrology",
    teacher: "Arvindrun Vnjay",
    tagline: "Determine the likelihood of having children, challenges, and timing of childbirth.",
    description:
      "Determine the likelihood of having children, potential challenges, and the timing of childbirth.",
    price: 3000,
    originalPrice: 6999,
    badge: "Featured",
    buyUrl: courseStore(505625),
    image: "/images/courses/progeny-astrology.png",
    features: ["Video lectures", "Files included", "Video access"],
    syllabus: ["5th house & progeny", "Child-delivery yogas", "Obstacle combinations", "Timing of childbirth", "Remedies"],
    duration: "Validity: 12 months",
  },
  {
    slug: "profession-career-astrology",
    title: "Profession & Career Astrology",
    type: "recorded",
    category: "astrology",
    teacher: "Arvindrun Vnjay",
    tagline: "Career guidance through the birth chart — strengths & timing of opportunity.",
    description:
      "Analyzes a person's birth chart to offer guidance on career choices, strengths & timing of opportunity.",
    price: 3000,
    originalPrice: 6999,
    badge: "Featured",
    buyUrl: courseStore(536605),
    image: "/images/courses/profession-career-astrology.png",
    features: ["Video lectures", "Files included", "Video access"],
    syllabus: ["10th house & career", "Significators of profession", "Career change timing", "Business vs job analysis", "Case studies"],
    duration: "Validity: 12 months",
  },
  {
    slug: "bhrigu-chakra-padhati",
    title: "Bhrigu Chakra Padhiti",
    type: "recorded",
    category: "astrology",
    teacher: "Arvindrun Vnjay",
    tagline: "Ancient Vedic method to predict life events, reveal karma, and guide destiny.",
    description:
      "Bhrigu Chakra Padhiti is an ancient Vedic astrology method to predict life events, reveal karma, and guide destiny.",
    price: 1500,
    originalPrice: 2999,
    badge: "Featured",
    buyUrl: courseStore(653075),
    image: "/images/courses/bhrigu-chakra-padhati.png",
    features: ["Video lectures", "Files included", "Video access"],
    syllabus: ["Bhrigu Chakra fundamentals", "Sapthamsa & Navamsa usage", "Event prediction techniques", "Karma reading", "Practice charts"],
    duration: "Validity: 9 months",
  },
  {
    slug: "pythagorean-numerology",
    title: "Pythagorean Numerology",
    type: "recorded",
    category: "numerology",
    teacher: "Arvindrun Vnjay",
    tagline: "The numerology system that connects numbers to personality, destiny, and purpose.",
    description:
      "It is a type of numerology system that connects numbers to personality, destiny, and purpose.",
    price: 2500,
    originalPrice: 3999,
    buyUrl: courseStore(504051),
    image: "/images/courses/pythagorean-numerology.png",
    features: ["Video lectures", "Video access"],
    syllabus: ["Pythagorean table", "Life path & destiny numbers", "Expression & soul urge", "Western vs Vedic comparison"],
    duration: "Validity: 9 months",
  },
  {
    slug: "prediction-from-currency-notes",
    title: "Predict & Improve Your Financial Condition By Currency Note",
    type: "recorded",
    category: "numerology",
    teacher: "Arvindrun Vnjay",
    tagline: "Certain serial number combinations hold special meaning or can influence wealth & fortune.",
    description:
      "Certain serial number combinations hold special meaning or can influence wealth & fortune.",
    price: 999,
    originalPrice: 1999,
    badge: "Featured",
    buyUrl: courseStore(503673),
    image: "/images/courses/prediction-from-currency-notes.png",
    features: ["Video lectures", "Video access"],
    syllabus: ["Serial number analysis", "Combinations & meanings", "Wealth predictions", "Practical usage"],
    duration: "Validity: 3 months",
  },
  {
    slug: "wealth-prosperity-foreign-astrology",
    title: "Wealth Prosperity Foreign Astrology",
    type: "recorded",
    category: "astrology",
    teacher: "Arvindrun Vnjay",
    tagline: "Time events & understand issues related to Wealth, Property & Foreign settlement & Travel.",
    description:
      "You can time events & also understand the issues related to Wealth Property & Foreign settlement & Travel.",
    price: 3000,
    originalPrice: 6999,
    badge: "Featured",
    buyUrl: courseStore(524835),
    image: "/images/courses/wealth-prosperity-foreign-astrology.png",
    features: ["Video lectures", "Files included", "Video access"],
    syllabus: ["Wealth houses & yogas", "Property indicators", "Foreign settlement combinations", "Travel timing", "Case studies"],
    duration: "Validity: 12 months",
  },
  {
    slug: "complete-vastu-course",
    title: "Complete Vastu Course from Basic to Advance",
    type: "recorded",
    category: "vastu",
    teacher: "Arvindrun Vnjay",
    tagline: "The full Vastu Shastra journey — from absolute basics to professional-level practice.",
    description:
      "The most comprehensive Vastu training we offer. From the foundations of direction science to professional-level zone correction, this course takes you from a complete beginner to a confident Vastu consultant.",
    price: 15000,
    originalPrice: 24999,
    badge: "Full Course",
    buyUrl: "https://www.arvinastro.com/courses/788759",
    image: "/images/courses/complete-vastu-course-basic-to-advance.png",
    features: ["Video lectures", "Files included", "Video access", "Certificate"],
    syllabus: ["Vastu foundations", "16 zones in depth", "Devta energies", "Toilet & kitchen corrections", "Business & home Vastu", "Professional practice setup"],
    duration: "Validity: 12 months",
  },

  // ===================== RECORDED (New) =====================
  {
    slug: "medical-vastu-numerology",
    title: "Medical & Vastu Numerology",
    type: "recorded",
    category: "numerology",
    teacher: "Arvindrun Vnjay",
    tagline: "Combine numerology with vastu and health insights to predict and correct well-being.",
    description:
      "Learn how numerology connects with vastu and health. This course teaches you to analyze numbers for health predictions and use vastu-numerology combinations for effective remedies.",
    price: 2000,
    originalPrice: 3999,
    buyUrl: "https://www.arvinastro.com/courses/780730",
    image: "/images/courses/medical-vastu-numerology.png",
    features: ["Video lectures", "Video access", "Certificate"],
    syllabus: ["Numbers & health mapping", "Medical numerology indicators", "Vastu & number alignment", "Remedies & case studies"],
    duration: "Validity: 9 months",
  },
  {
    slug: "surya-paddhati",
    title: "Surya Paddhati — Sun Progression Method",
    type: "recorded",
    category: "astrology",
    teacher: "Arvindrun Vnjay",
    tagline: "Predict events and time life phases using the powerful Sun-based progression system.",
    description:
      "Surya Paddhati is a Sun Progression Method that gives remarkable timing of events. Learn this precise predictive technique for accurate event timing in consultations.",
    price: 1500,
    originalPrice: 3999,
    buyUrl: "https://www.arvinastro.com/courses/504477",
    image: "/images/courses/surya-paddhati.png",
    features: ["Video lectures", "Video access", "Certificate"],
    syllabus: ["Surya Paddhati fundamentals", "Sun progression calculations", "Event timing techniques", "Practice charts"],
    duration: "Validity: 9 months",
  },

  // ===================== FREE =====================
  {
    slug: "learn-jagannath-hora-software",
    title: "Learn Jagannath Hora Software",
    type: "free",
    teacher: "Arvindrun Vnjay",
    tagline: "Learn to use Jagannatha Hora Astrology software in detail with few secrets of astrology.",
    description:
      "Learn to use Jagannatha Hora Astrology software in detail with few secrets of Astrology. Video language: Hindi. The perfect free starting point to practice charts.",
    youtubeUrl: "https://www.youtube.com/playlist?list=PLn1-1oorZ6H5VtgFrOOcBtIm7cMImJil5",
    image: "/images/courses/free-hora.svg",
    features: ["Free YouTube playlist", "Hindi language", "Beginner friendly"],
  },
  {
    slug: "marriage-astrology-free",
    title: "Marriage Astrology (Free Series)",
    type: "free",
    teacher: "Arvindrun Vnjay",
    tagline: "Know all about marriage — good or bad marriage, timing & no-marriage conditions.",
    description:
      "In this course you will get to know all about marriage like good or bad marriage, how to time marriage & no marriage etc. A complete free series on marriage astrology.",
    youtubeUrl: "https://www.youtube.com/playlist?list=PLn1-1oorZ6H5jNXRW-0IqFgXQ7w4L2p2m",
    image: "/images/courses/free-marriage.svg",
    features: ["Free YouTube playlist", "Hindi language", "Real chart examples"],
  },
  {
    slug: "learn-32-vastu-entrances",
    title: "Learn 32 Vastu Entrances",
    type: "free",
    teacher: "Arvindrun Vnjay",
    tagline: "Know all 32 Vastu entrances results with symptoms & remedies.",
    description:
      "In this course you will get to know all 32 vastu entrances results with symptoms & remedies. A unique free series that gives deep Vastu knowledge.",
    youtubeUrl: "https://www.youtube.com/playlist?list=PLn1-1oorZ6H4B2iUtG2ZIBQPY-O3ETFFi",
    image: "/images/courses/free-vastu-entrances.svg",
    features: ["Free YouTube playlist", "Hindi language", "32 entrances explained"],
  },
  {
    slug: "vastu-symbolic-remedies",
    title: "Vastu Symbolic Remedies For All Directions",
    type: "free",
    teacher: "Arvindrun Vnjay",
    tagline: "Learn all Vastu symbolic remedies for all directions.",
    description:
      "In this course you will get to know all vastu symbolic remedies for all directions. Simple, practical remedies you can apply immediately.",
    youtubeUrl: "https://www.youtube.com/playlist?list=PLn1-1oorZ6H57QPb2Lh7iV0ajI4Pu8OsK",
    image: "/images/courses/free-remedies.svg",
    features: ["Free YouTube playlist", "Hindi language", "Direction-wise remedies"],
  },

  // ===================== LIVE =====================
  {
    slug: "predictive-numerology-course",
    title: "Predictive Numerology Course",
    type: "live",
    teacher: "Arvindrun Vnjay",
    tagline: "Master Predictions in 2026",
    description:
      "Discover how numbers influence your life with our easy-to-follow Numerology Masterclass. This course is perfect for beginners and anyone curious about the mystical world of numbers. In this advanced-level program, you will learn how to analyze and predict life events, health issues, relationships, and business success—just by using a name and date of birth.",
    about:
      "🚨 ALERT: Sirf ₹999/- Pay kare aur apni seat book kare for this in depth amazing scientific Journey. TOTAL FEES ₹14999/ – Only",
    whyJoin: [
      "Learn from an Expert: Instructor ke paas bahut gehri knowledge aur 8+ saal ka professional experience hai, unse seekhein numbers ke saare raaz.",
      "Comprehensive Curriculum: Ek poora course jo Numerology ki saari main branches aur practical areas ko detail mein cover karta hai.",
      "High Value Course: Is course ki market price Rs. 70,000+ hai, lekin aap ise bahut hi affordable value par seekh rahe hai.",
    ],
    perks: [
      "Live Classes: Har hafte 3 Live Classes hongi.",
      "Certification: Course poora hone ke baad aapko Certificate milega, jo aapki professional credibility ko badhayega.",
      "Easy Start: ₹999/- Pay pay karein, Balance Payment When Course Starts .LIMITED SEATS AVIALABLE .",
      "TOTAL FEES ₹14999/ – Only",
      "Class Recording Access For 12 Months",
    ],
    startsFrom: "Starting From September 2026",
    price: 999,
    payUrl: "https://u.payu.in/PAYUMN/Ar42LpaN1Bo2",
    priceSuffix: "",
    image: "/images/courses/live-predictive-numerology.png",
    features: [
      "Live interactive classes — 3 sessions every week",
      "Certificate on completion",
      "Class Recording Access For 12 Months",
      "Balance Payment When Course Starts",
    ],
    duration: "3 live classes every week · Recording access for 12 months",
    syllabus: [
      "Lo Shu Numerology Mastery: Isme hum 9-Key method aur 2 powerful ways seekhenge jis se aap apni Lucky Direction khud dhoond sakte hain.",
      "Pythagorean Numerology: Is module mein aap master predictions karna seekhenge jo birth dates aur deep name analysis par based hoti hain.",
      "Vedic Numerology Secrets: Hamare Predictive Numerology Course mein aap traditional Indian system ko Astrology ke sath connect karke dekhna seekhenge.",
      "Indian & Mobile Numerology: Decode karein ki aapka mobile number aur personal numbers aapki personality ke baare mein kya batate hain.",
      "Medical Numerology: Numbers ke pattern se health indicators ko pehchanna aur remedies find karna seekhein.",
      "Horary & Time Numerology: Seekhein kaise current time aur instant calculations se kisi bhi sawal ka turant jawab diya jata hai.",
      "Numero Vastu Integration: Numbers ki power ko use karke apne ghar aur office mein harmony aur balance kaise layein, ye is Predictive Numerology Course ka ek khaas hissa hai.",
      "Scientific Match Making: Relationships aur business partnerships ke liye perfect compatibility check karna seekhein numeric tools se.",
      "Universal Zodiac Systems: Indian, Western, aur Chinese signs ka ek unique blend jo aapko ek complete expert banayega.",
      "Important Note: Hamara ye Predictive Numerology Course online live sessions ke madhyam se sikhaya jata hai. Join our Predictive Numerology Course today for a bright future in occult science.",
    ],
  },
  {
    slug: "complete-basic-to-advanced-vastu-course",
    title: "Complete Basic To Advanced Vastu Course",
    type: "live",
    teacher: "Arvindrun Vnjay",
    tagline: "5 Key Pillars",
    description:
      "Welcome to our Complete Basic To Advanced Vastu Course, where you will learn the most scientific and logical ways to balance your space for health and prosperity.",
    about:
      "Master the ancient science of energy balancing with our comprehensive Vastu course, bridging the gap between traditional wisdom and modern medical contexts. Learn precise mapping, 45 Deva analysis, and scientific remedies to harmonize living spaces for health, wealth, and prosperity. 🚨 ALERT: Sirf ₹299/- (Around 42 classes), pehle 1st class ki fees dein, aur apni seat book kare for this in depth amazing scientific Journey.",
    whyJoin: [
      "Expert Insights: Learn directly from Arvindrun Vnjay, an expert with deep knowledge in both Vastu and Medical Vastu.",
      "Logic-Based Learning: Move beyond myths and understand the scientific reasoning behind every Vastu principle.",
      "Holistic Approach: A unique curriculum that integrates directional analysis with health and well-being.",
    ],
    perks: [
      "Weekly 3 Live Sessions: Har hafte Sir ke saath Live Interactive Session join karein.",
      "Step-by-Step Mastery: Hum focus karte hain ki aap har concept ko master karein.",
      "Lifetime Community Access: Hamare dedicated student group ka Lifetime Access payein. Humesha ke liye networking, updates, aur knowledge sharing se jude rahein.",
      "Free Bar Chart & Center Marking Software Worth Rs.5500/-",
    ],
    startsFrom: "Starting From October 2026",
    price: 299,
    payUrl: "https://u.payu.in/PAYUMN/BICnl70s1cEZ",
    priceSuffix: "",
    image: "/images/courses/live-complete-vastu.png",
    features: ["Live interactive classes", "Class Recording Access For 12 Months", "Certificate After Completing the Course", "Free Bar Chart & Center Marking Software", "Lifetime community access"],
    duration: "₹299 · 3 live classes every week · Recording access for 12 months",
    syllabus: [
      "Foundation & Mapping Mastery: Scientific Plot Analysis and taking accurate degrees. Google Earth Pro. Precise Gridding and calculating the Brahmasthan (Central Point).",
      "16 Directions & Their Attributes: Deep study of 16 Vastu Zones — their specific energies, colors, and impact on life. How to balance each zone to improve Health, Money, and Relationships.",
      "Placement & Scientific Treatments: Entrance Analysis — Detailed study of 32 Entrances and their effects. Modern Treatments — Scientific remedies for the Main Gate, Kitchen, and Toilets. Advanced Fixes — Balancing “T-Hits” and other complex structural defects.",
      "Medical Vastu: Medical Vastu — Linking directions with specific health issues and healing. Data Analysis — Learn Brahmastra calculations and Vastu Bar Charts for accurate diagnosis.",
      "The 45 Devas & Advanced Remedies: Comprehensive study of the 45 Energy Fields (Devas) in the Vastu Purusha Mandala. Applying symbolic and advanced remedies without any structural demolition.",
      "Who Can Benefit? Aspiring Professionals — Anyone looking to create a Rewarding Part-Time or Full-Time Earning Source by becoming a certified Vastu Consultant. Healthcare Professionals — Doctors and healers looking for holistic environmental healing to complement medical treatments. Architects & Interior Designers — Professionals wanting to add Vastu as a premium, value-added service to their existing projects. Existing Vastu Consultants — Practitioners aiming to upgrade their traditional knowledge to an advanced, logic-based level. Homeowners & Seekers — Individuals seeking to create a high-vibration living space for the health and prosperity of their family.",
    ],
  },
  {
    slug: "predictive-name-numerology-course",
    title: "Predictive Name Numerology Course",
    type: "live",
    teacher: "Arvindrun Vnjay",
    tagline: "Unlock Powerful Success",
    description:
      "Welcome to our Predictive Name Numerology Course, where you will discover how your name's vibration can unlock doors to massive success and wealth.",
    about:
      "Design Powerful Names. Predict with Precision. Unlock the deeper science of Name Numerology & Pronology in this powerful course designed for those who want to go beyond the basics. Learn to analyse, correct, and design names that attract success, health, harmony, and spiritual growth. TOTAL FEES ₹15999/ – Only 🚨 ALERT: Sirf ₹999/- Pay Karein aur apni seat book kare for this in depth amazing scientific Journey. Pay Balance Payment When Course Starts",
    whyJoin: [
      "In-depth Learning of predictive techniques, not just theory",
      "Live Practical Examples for real-time understanding",
      "Personal attention to All Students",
      "Guidance by an Expert with years of hands-on experience",
      "Unique Techniques you won't find anywhere else",
    ],
    perks: [
      "3 Classes per Week",
      "Certificate: Get a certificate upon completion of course.",
      "Easy Start: Sirf Class 1 ki fees pay karein, pehli class attend karein aur wahan aapko baaki saari course details mil jayengi.",
      "TOTAL FEES ₹15999/ – Only",
      "LIMITED SEATS AVAIALBLE",
    ],
    startsFrom: "Starting in September 2026",
    price: 999,
    payUrl: "https://u.payu.in/PAYUMN/EIHnO7MsScDH",
    priceSuffix: "",
    image: "/images/courses/live-predictive-name.png",
    features: ["Live interactive classes", "Class Recording Access For 12 Months", "Certificate After Completing the Course", "Pay Balance Payment When Course Starts"],
    duration: "₹999 booking · 3 live classes every week · Recording access for 12 months",
    syllabus: [
      "Graphology",
      "ALPHABETS",
      "Repeated & Missing Alphabets",
      "Weak Balanced Number Concept",
      "Zodiac",
      "Compounds",
      "Hidden Numbers in Name",
      "How to Multiply any Alphabet in Name",
      "How to Predict from Name",
      "2 Type of Gridding",
      "Compounds Combination",
      "How to see Events Years form Name",
      "Pronology",
      "Medical Pronology",
      "Alphabets Combination in Name",
      "Cycle Concept",
      "MD AD Calculation from Name",
      "Combination & Macron",
      "How to choose First Alphabet of Name",
      "Many Tips & Trick to Predict from Name",
    ],
  },
  {
    slug: "prashna-kundali",
    title: "Prashna Kundali",
    type: "live",
    teacher: "Arvindrun Vnjay",
    tagline: "",
    description:
      "Why Learn Prashna Kundali? Instant Solutions: Provide real-time answers based on the moment a query is raised. No Birth Details Needed: Perfect for clients who don't have their exact time or date of birth. High Accuracy: Focuses on the Avastha of the mind and the cosmos at the time of the question, making it a highly reliable branch of Astrology. Practical & Result-Oriented: A must-have tool for every practicing astrologer to refine their predictions. Don't miss this chance to master one of the most powerful tools in Ancient Science.",
    price: 4999,
    payUrl: "https://u.payu.in/Lrb65azH7KKh",
    priceSuffix: "",
    image: "/images/courses/live-prashna-kundali.png",
    features: ["Live interactive classes", "Includes 6 months of recording validity"],
    startsFrom: "Course Starting VERY SOON",
  },
];

export const RECORDED_COURSES = COURSES.filter((c) => c.type === "recorded");
export const FREE_COURSES = COURSES.filter((c) => c.type === "free");
export const LIVE_COURSES = COURSES.filter((c) => c.type === "live");

export function getCourse(slug: string) {
  return COURSES.find((c) => c.slug === slug);
}
