export type SiteFieldType = "text" | "textarea" | "url" | "list" | "json" | "image" | "courses";
export type SiteField = { key: string; label: string; type?: SiteFieldType; hint?: string };
export type SitePage = { slug: string; title: string; icon: string; fields: SiteField[] };

export const SITE_PAGES: SitePage[] = [
  {
    slug: "global",
    title: "Global Settings",
    icon: "⚙️",
    fields: [
      { key: "siteName", label: "Site Name" },
      { key: "siteTagline", label: "Site Tagline" },
      { key: "logoUrl", label: "Logo", type: "image" },
      { key: "phoneMain", label: "Main Phone Number" },
      { key: "phoneSecondary", label: "Secondary Phone" },
      { key: "whatsappCommunity", label: "WhatsApp Community Link", type: "url" },
      { key: "email", label: "Email Address" },
      { key: "address", label: "Address" },
      { key: "instagram", label: "Instagram URL", type: "url" },
      { key: "youtube", label: "YouTube URL", type: "url" },
      { key: "facebook", label: "Facebook URL", type: "url" },
      { key: "announcement", label: "Top Announcement Bar", type: "textarea" },
      { key: "navJson", label: "Navigation Menu (JSON)", type: "json", hint: "Array of {label,href,children?:[{label,href}]}" },
      { key: "appsIos", label: "iOS App URL", type: "url" },
      { key: "appsAndroid", label: "Android App URL", type: "url" },
      { key: "copyright", label: "Footer Copyright" },
    ],
  },
  {
    slug: "home",
    title: "Home Page",
    icon: "🏠",
    fields: [
      { key: "heroTitle", label: "Hero Title (text overlay)", type: "textarea" },
      { key: "heroSubtitle", label: "Hero Subtitle (text overlay)", type: "textarea" },
      { key: "heroImage1", label: "Hero Image 1 (Desktop)", type: "image", hint: "Upload or paste a wide 16:9 carousel image" },
      { key: "heroImage2", label: "Hero Image 2 (Desktop)", type: "image" },
      { key: "heroImage3", label: "Hero Image 3 (Desktop)", type: "image" },
      { key: "heroImage4", label: "Hero Image 4 (Desktop)", type: "image" },
      { key: "heroImage5", label: "Hero Image 5 (Desktop)", type: "image" },
      { key: "heroImageMobile", label: "Hero Image (Mobile portrait)", type: "image", hint: "Single portrait 9:16 image for mobile" },
      { key: "aboutText", label: "About Strip Text", type: "textarea" },
      { key: "expertImage", label: "Expert Photo (About Strip)", type: "image" },
      { key: "expertName", label: "Expert Name" },
      { key: "expertText", label: "Expert Intro Text", type: "textarea" },
      { key: "aboutDidYouKnow", label: "Did You Know — Text", type: "textarea" },
      { key: "aboutLongText", label: "Stats Paragraph (after Did You Know)", type: "textarea" },
      { key: "aboutBoxes", label: "3 Feature Boxes (JSON)", type: "json", hint: "Array of {icon,title,desc}. Icons: sparkle, users, heart" },
      { key: "aboutBadgeValue", label: "Photo Badge Number (e.g. 8+)" },
      { key: "aboutBadgeLabel", label: "Photo Badge Label (two lines via newline)", type: "textarea" },
      { key: "aboutKicker", label: "About Section — Kicker (small text above title)" },
      { key: "transitKicker", label: "Transits — Kicker" },
      { key: "transitTitle", label: "Transits — Heading" },
      { key: "transitDesc", label: "Transits — Description", type: "textarea" },
      { key: "horoscopeKicker", label: "Horoscope — Kicker" },
      { key: "horoscopeTitle", label: "Horoscope — Heading" },
      { key: "horoscopeDesc", label: "Horoscope — Description", type: "textarea" },
      { key: "servicesKicker", label: "Services — Kicker" },
      { key: "servicesTitle", label: "Services — Heading" },
      { key: "servicesDesc", label: "Services — Description", type: "textarea" },
      { key: "coursesKicker", label: "Courses — Kicker" },
      { key: "coursesTitle", label: "Courses — Heading" },
      { key: "coursesDesc", label: "Courses — Description", type: "textarea" },
      { key: "journeyKicker", label: "Journey — Kicker" },
      { key: "journeyTitle", label: "Journey — Heading" },
      { key: "youtubeKicker", label: "YouTube — Kicker" },
      { key: "youtubeTitle", label: "YouTube — Heading" },
      { key: "youtubeDesc", label: "YouTube — Description", type: "textarea" },
      { key: "testimonialsKicker", label: "Testimonials — Kicker" },
      { key: "testimonialsTitle", label: "Testimonials — Heading" },
      { key: "testimonialsDesc", label: "Testimonials — Description", type: "textarea" },
      { key: "appKicker", label: "App — Kicker" },
      { key: "appTitle", label: "App — Heading" },
      { key: "appDesc1", label: "App — Description Line 1", type: "textarea" },
      { key: "appDesc2", label: "App — Description Line 2 (iOS ORG code)", type: "textarea" },
      { key: "blogKicker", label: "Blog — Kicker" },
      { key: "blogTitle", label: "Blog — Heading" },
      { key: "blogDesc", label: "Blog — Description", type: "textarea" },
      { key: "waKicker", label: "WhatsApp Community — Kicker" },
      { key: "waTitle", label: "WhatsApp Community — Heading" },
      { key: "waDesc", label: "WhatsApp Community — Description", type: "textarea" },
      { key: "ctaKicker", label: "CTA — Kicker" },
      { key: "ctaDesc", label: "CTA — Description", type: "textarea" },
      { key: "featuredCourseSlugs", label: "Learn & Grow — Featured Courses", type: "courses", hint: "Pick which courses appear in the Home 'Master the Cosmic Sciences' section (3 recommended)" },
      { key: "youtubeVideos", label: "YouTube Shorts (URLs)", type: "list", hint: "One YouTube URL per line — up to 4 or more" },
      { key: "ctaText", label: "CTA Heading", type: "textarea" },
    ],
  },
  {
    slug: "marquee",
    title: "Sliding Text (Marquee)",
    icon: "🔄",
    fields: [
      { key: "homeMarquee", label: "Home Page — Sliding Text (below hero)", type: "list", hint: "One item per line — e.g. Astrologer, Name Numerology Expert…" },
      { key: "aboutMarquee", label: "About Page — Sliding Text", type: "list", hint: "One item per line — e.g. Vedic Astrology, Kundli Analysis…" },
    ],
  },
  {
    slug: "about",
    title: "About Page",
    icon: "👤",
    fields: [
      { key: "heroTitle", label: "Profile Name / Hero Title" },
      { key: "heroSubtitle", label: "Hero Subtitle", type: "textarea" },
      { key: "aboutHeroBg", label: "Hero Background Image", type: "image", hint: "Full-width background image for the About page hero section" },
      { key: "aboutRoles", label: "Role Chips (below photo)", type: "list", hint: "One role per line — e.g. Astrologer, Name Numerology Expert…" },
      { key: "bioWelcome", label: "Welcome Paragraph (drop-cap W)", type: "textarea", hint: "Use **text** for bold highlights" },
      { key: "badgeValue", label: "Photo Badge Number (e.g. 8+)" },
      { key: "badgeLabel", label: "Photo Badge Label (two lines via newline)", type: "textarea" },
      { key: "journeyKicker", label: "Chapter 1 — Kicker" },
      { key: "journeyTitle", label: "Chapter 1 — Heading" },
      { key: "journeyText", label: "Chapter 1 — Text", type: "textarea", hint: "Use **text** for bold highlights" },
      { key: "offerKicker", label: "Chapter 2 — Kicker" },
      { key: "offerTitle", label: "Chapter 2 — Heading" },
      { key: "offerText", label: "Chapter 2 — Text (blank line = new paragraph)", type: "textarea", hint: "Use **text** for bold highlights" },
      { key: "quoteMain", label: "Quote — Main Line", type: "textarea", hint: "Use __text__ for accent word" },
      { key: "quoteSub", label: "Quote — Small Line", type: "textarea" },
      { key: "promiseKicker", label: "Chapter 3 — Kicker" },
      { key: "promiseTitle", label: "Chapter 3 — Heading" },
      { key: "promiseText", label: "Chapter 3 — Text (blank line = new paragraph)", type: "textarea", hint: "Use **text** for bold highlights" },
      { key: "globalTitle", label: "Global Consultation — Title" },
      { key: "globalText", label: "Global Consultation — Text", type: "textarea" },
      { key: "locationTitle", label: "Location — Title" },
      { key: "locationText", label: "Location — Text", type: "textarea" },
      { key: "bio", label: "Bio / About Text", type: "textarea" },
      { key: "aboutImage", label: "Profile Photo", type: "image" },
      { key: "statYears", label: "Years of Experience" },
      { key: "statStudents", label: "Students Enrolled" },
      { key: "statConsultations", label: "Consultations Given" },
      { key: "whyTitle", label: "Why Section Title" },
      { key: "whyBoxes", label: "6 Feature Boxes (JSON)", type: "json", hint: "Array of {icon,title,desc}. Icons: sparkle, users, award, heart, check, phone" },
    ],
  },
  {
    slug: "services",
    title: "Services Page",
    icon: "✨",
    fields: [
      { key: "heroTitle", label: "Main Heading" },
      { key: "heroSubtitle", label: "Main Description", type: "textarea" },
      { key: "whyTitle", label: "Why Choose Us Title" },
      { key: "whyText", label: "Why Choose Us Text", type: "textarea" },
    ],
  },
  {
    slug: "courses",
    title: "Courses Page",
    icon: "🎓",
    fields: [
      { key: "heroTitle", label: "Main Heading" },
      { key: "heroSubtitle", label: "Main Description", type: "textarea" },
    ],
  },
  {
    slug: "courses-recorded",
    title: "Recorded Courses Page",
    icon: "🎬",
    fields: [
      { key: "heroTitle", label: "Main Heading" },
      { key: "heroSubtitle", label: "Main Description", type: "textarea" },
    ],
  },
  {
    slug: "courses-free",
    title: "Free Courses Page",
    icon: "🆓",
    fields: [
      { key: "heroTitle", label: "Main Heading" },
      { key: "heroSubtitle", label: "Main Description", type: "textarea" },
    ],
  },
  {
    slug: "courses-live",
    title: "Live Courses Page",
    icon: "🔴",
    fields: [
      { key: "heroTitle", label: "Main Heading" },
      { key: "heroSubtitle", label: "Main Description", type: "textarea" },
    ],
  },
  {
    slug: "books",
    title: "Books Page",
    icon: "📚",
    fields: [
      { key: "heroTitle", label: "Main Heading" },
      { key: "heroSubtitle", label: "Main Description", type: "textarea" },
    ],
  },
  {
    slug: "vastu-products",
    title: "Vastu Products Page",
    icon: "📦",
    fields: [
      { key: "heroTitle", label: "Breadcrumb Heading" },
      { key: "heroSubtitle", label: "Main Description", type: "textarea" },
    ],
  },
  {
    slug: "blog",
    title: "Blog Page",
    icon: "📰",
    fields: [
      { key: "heroTitle", label: "Main Heading" },
      { key: "heroSubtitle", label: "Main Description", type: "textarea" },
    ],
  },
  {
    slug: "contact",
    title: "Contact Page",
    icon: "📞",
    fields: [
      { key: "heroTitle", label: "Main Heading" },
      { key: "heroSubtitle", label: "Hero Subtitle", type: "textarea" },
      { key: "contactHeading", label: "Contact Heading" },
      { key: "contactDesc", label: "Contact Description", type: "textarea" },
      { key: "contactPhone", label: "Phone Number" },
      { key: "contactWhatsapp", label: "WhatsApp Number" },
      { key: "contactWaLink", label: "Direct WhatsApp Link (wa.me/...)", type: "url", hint: "Paste the full link like https://wa.me/919718646655?text=..." },
      { key: "contactEmail", label: "Email" },
      { key: "contactLocation", label: "Location" },
      { key: "contactAvailability", label: "Availability Hours" },
    ],
  },
  {
    slug: "footer",
    title: "Footer",
    icon: "📎",
    fields: [
      { key: "copyright", label: "Copyright Text" },
      { key: "tagline", label: "Footer Tagline" },
    ],
  },
  {
    slug: "notice",
    title: "Offers Popup (Hero Slider)",
    icon: "📢",
    fields: [
      { key: "noticeEnabled", label: "Show offers popup (true/false)", hint: "Set to true to show the popup site-wide" },
      { key: "noticeInterval", label: "Auto-slide interval (ms)", hint: "e.g. 4000 for 4s per slide" },
      { key: "noticeImage1", label: "Slide 1 — Image", type: "image", hint: "Recommended 800×500" },
      { key: "noticeTitle1", label: "Slide 1 — Heading" },
      { key: "noticeDesc1", label: "Slide 1 — Description", type: "textarea" },
      { key: "noticeLink1", label: "Slide 1 — Link URL", type: "url", hint: "Where the card navigates on click; external opens new tab" },
      { key: "noticeImage2", label: "Slide 2 — Image", type: "image" },
      { key: "noticeTitle2", label: "Slide 2 — Heading" },
      { key: "noticeDesc2", label: "Slide 2 — Description", type: "textarea" },
      { key: "noticeLink2", label: "Slide 2 — Link URL", type: "url" },
      { key: "noticeImage3", label: "Slide 3 — Image", type: "image" },
      { key: "noticeTitle3", label: "Slide 3 — Heading" },
      { key: "noticeDesc3", label: "Slide 3 — Description", type: "textarea" },
      { key: "noticeLink3", label: "Slide 3 — Link URL", type: "url" },
    ],
  },
  {
    slug: "terms",
    title: "Terms & Conditions",
    icon: "📜",
    fields: [
      { key: "content", label: "Full Terms & Conditions Content", type: "textarea", hint: "Paste the complete Terms & Conditions text here" },
    ],
  },
  {
    slug: "privacy",
    title: "Privacy Policy",
    icon: "🔒",
    fields: [
      { key: "content", label: "Full Privacy Policy Content", type: "textarea", hint: "Paste the complete Privacy Policy text here" },
    ],
  },
];

const DEFAULT_NAV = [
  { label: "Home", href: "/" },
  { label: "About Us", href: "/about" },
  {
    label: "Courses",
    href: "/courses",
    children: [
      { label: "Recorded Courses", href: "/courses/recorded" },
      { label: "Free Courses", href: "/courses/free" },
      { label: "Live Courses", href: "/courses/live" },
    ],
  },
  { label: "Services", href: "/services" },
  { label: "Books", href: "/books" },
  { label: "Vastu Products", href: "/vastu-products" },
  { label: "Blog", href: "/blog" },
  { label: "Contact", href: "/contact" },
  { label: "Admin Login", href: "/admin" },
];

export const SITE_DEFAULTS: Record<string, Record<string, string>> = {
  global: {
    siteName: "Arvin Astro",
    siteTagline: "Align Your Karma with Cosmic Energy.",
    logoUrl: "/images/logo.png",
    phoneMain: "+91 97186 46655",
    phoneSecondary: "",
    whatsappCommunity: "https://wa.me/919718646655",
    email: "info@arvinastro.in",
    address: "Sector 16B, Greater Noida West, UP, India",
    instagram: "https://www.instagram.com/arvin_astro/",
    youtube: "https://www.youtube.com/@arvinastro",
    facebook: "https://www.facebook.com/arvinastro112/",
    announcement:
      "🚀 New batches starting soon — Join our Live Courses!  Book consultations for Kundli, Vastu & Name Numerology.",
    navJson: JSON.stringify(DEFAULT_NAV),
    appsIos: "https://apps.apple.com/us/app/classplus/id1324522260",
    appsAndroid: "https://play.google.com/store/apps/details?id=co.iron.ruvvu&pcampaignid=web_share",
    copyright: "© 2022-2026 arvinastro.in | All Rights Reserved",
  },
  home: {
    heroTitle: "",
    heroSubtitle: "",
    heroImage1: "/images/hero-desktop.png",
    heroImage2: "",
    heroImage3: "",
    heroImageMobile: "/images/hero-mobile.png",
    aboutText:
      "A passionate practitioner of ancient Vedic sciences, helping individuals discover their true potential through celestial insights.",
    expertImage: "/images/about.png",
    expertName: "Arvindrun Vnjay",
    expertText:
      "A passionate practitioner of ancient Vedic sciences, helping individuals discover their true potential through celestial insights.",
    featuredCourseSlugs: "[]",
    aboutKicker: "About the Expert",
    aboutDidYouKnow: "**Did you know?** Arvindrun Vnjay is the pioneer who first integrated **Ancient Astrology** into **Advanced Modern Name Numerology**. He created a revolution in the industry that many now follow — you are connecting with the original expert who changed the way we look at destiny!",
    aboutLongText: "With over **8 years of dedicated practice**, he has guided **2666+ students** and provided **999+ consultations** globally through the transformative wisdom of Astrology, Name Numerology, and Vastu Shastra. His approach combines traditional Vedic knowledge with practical, modern application — he sees himself not as a predictor, but as a bridge connecting you to the ancient, profound wisdom held in the stars, the rhythm of numbers, and the silent language of your home.",
    aboutBoxes: JSON.stringify([
      { icon: "sparkle", title: "Vedic Astrology", desc: "Deep kundli analysis & life predictions" },
      { icon: "users", title: "Name Numerology", desc: "Cosmic alignment through names" },
      { icon: "heart", title: "Vastu Shastra", desc: "Spatial harmony for prosperity" },
    ]),
    aboutBadgeValue: "8+",
    aboutBadgeLabel: "Years of\nPractice",
    transitKicker: "Live Vedic Tracker",
    transitTitle: "Planetary Transits Today",
    transitDesc: "Live positions of the nine Vedic Gochar planets — Sidereal (Lahiri Ayanamsha)",
    horoscopeKicker: "Your Daily Cosmic Forecast based on Moon Sign",
    horoscopeTitle: "Daily Horoscope",
    horoscopeDesc: "Select your Moon Sign (Chandra Rashi) to reveal today's horoscope, lucky color, and lucky number.",
    servicesKicker: "What We Offer",
    servicesTitle: "Astrology & Vastu Services",
    servicesDesc: "Personalized Vedic astrology, name numerology, and Vastu consultations tailored to your life's challenges — from career and marriage to health and prosperity.",
    coursesKicker: "Learn & Grow",
    coursesTitle: "Master the **Cosmic Sciences**",
    coursesDesc: "A complete platform for Astrology, Numerology, Name Numerology & Vastu",
    journeyKicker: "How It Works",
    journeyTitle: "Your Journey With Us",
    youtubeKicker: "YouTube",
    youtubeTitle: "Watch & Learn",
    youtubeDesc: "Short clips from our live sessions and courses — subscribe for full-length content.",
    testimonialsKicker: "What Our Student and Client Says",
    testimonialsTitle: "What Our Students and Clients Say",
    testimonialsDesc: "Real reviews from our students and clients on Google",
    appKicker: "Learn Anywhere, Anytime",
    appTitle: "Take Arvin Astro with you — Download the App",
    appDesc1: "Download Our Mobile App to explore Free & Paid Contents",
    appDesc2: "To Download our app on iOS use above given link with ORG code \u201cAGAFHE\u201d",
    blogKicker: "From the Blog",
    blogTitle: "Latest Research & Insights",
    blogDesc: "Deep dives into astrology, numerology and vastu — by Arvindrun Vnjay",
    waKicker: "Stay Connected",
    waTitle: "Join our WhatsApp Community",
    waDesc: "Get free session updates, astrology tips & course announcements directly on WhatsApp.",
    ctaKicker: "Begin Your Cosmic Journey Today",
    ctaDesc: "Get personalized guidance on astrology, name numerology, and vastu for health, wealth, and happiness.",
    youtubeVideos: JSON.stringify([
      "https://youtu.be/XOT9V3g1DrA",
      "https://youtu.be/fjsBFTP-lH4",
      "https://youtu.be/IlGagLhP1yI",
      "https://youtu.be/u7mIDoYU7UA",
    ]),
    ctaText: "",
  },
  contact: {
    heroTitle: "Let's talk about our cosmic journey",
    heroSubtitle: "",
    contactHeading: "Let's talk about our cosmic journey",
    contactDesc:
      "Have questions about Astrology, Name Numerology, or Vastu? Reach out and our team will get back to you shortly.",
    contactPhone: "+91 97186 46655",
    contactWhatsapp: "+91 97186 46655",
    contactWaLink: "https://wa.me/919718646655?text=Hello%20Arvin%20Astro%2C%20I%20have%20a%20question.",
    contactEmail: "info@arvinastro.in",
    contactLocation: "Sector 16B, Greater Noida West, UP, India",
    contactAvailability: "Mon–Sun · 9:00 AM – 5:00 PM",
  },
  marquee: {
    homeMarquee: JSON.stringify([
      "Astrologer",
      "Name Numerology Expert",
      "Vastu Consultant",
      "Teacher",
      "Consultant",
      "Mentor",
      "Spiritual Guide",
    ]),
    aboutMarquee: JSON.stringify([
      "Vedic Astrology",
      "Name Numerology",
      "Vastu Shastra",
      "Kundli Analysis",
      "Remedial Astrology",
      "Bhrigu Nandi Nadi",
      "Prediction",
      "Matchmaking",
      "Business Naming",
      "Baby Naming",
      "Address Numerology",
      "Lal Kitab",
    ]),
  },
  about: {
    heroTitle: "About Arvindrun Vnjay",
    heroSubtitle: "Astrologer · Name Numerology Expert · Vastu Consultant · Teacher",
    aboutHeroBg: "/images/about-hero-bg.png",
    aboutRoles: JSON.stringify([
      "Astrologer",
      "Name Numerology Expert",
      "Vastu Consultant",
      "Teacher",
      "Consultant",
    ]),
    bioWelcome: "Welcome to **Arvin Astro** — your trusted destination for the ancient and life-transforming sciences of **Vedic Astrology**, **Name Numerology**, and **Vastu Shastra**. Whether you are seeking clarity in life, looking for the perfect name for your newborn, or wanting to harmonize your living or working space, you are at the right place.",
    badgeValue: "8+",
    badgeLabel: "Years of\nPractice",
    journeyKicker: "The Journey",
    journeyTitle: "Who I Am",
    journeyText: "I am **Arvindrun Vnjay** — a passionate **Astrologer**, **Name Numerologist**, and **Vastu Consultant** with over **8+ years of dedicated practice** in the field of occult and spiritual sciences. My journey began with a deep curiosity about the cosmic forces that shape human destiny, and over the years, this curiosity has blossomed into a lifelong mission — to guide souls toward clarity, balance, and purpose.",
    offerKicker: "What We Offer",
    offerTitle: "Services & Expertise",
    offerText: "Through **Arvin Astro**, I offer a comprehensive range of services including **live and recorded courses** in Astrology and Numerology, **personal consultations** for individuals and businesses, and **result-oriented remedies** rooted in ancient wisdom. With **2666+ students enrolled** and **999+ consultations delivered** globally, my work has touched lives across India and in countries like the **USA, UK, Canada, and Australia**.\n\nMy expertise spans across **Vedic Astrology** (including Bhrigu Nandi Nadi), **Name Numerology** (including Business Naming and Address Numerology), and **Vastu Shastra** for home, office, and factory. I also offer specialized services such as **Kundli Analysis**, **Matchmaking**, **Remedial Astrology**, **Lal Kitab**, **Property Consultation**, **Matchmaking Consultation**, **Business Consultation**, **Numerology Consultation**, and **Baby Naming**.",
    quoteMain: "I see myself not just as an astrologer, but as a __bridge__ — connecting you to the ancient, profound wisdom held in the stars, the rhythm of numbers, and the silent language of your home.",
    quoteSub: "The universe has written a magnificent story for you, and I am here simply to help you read the script with confidence and courage.",
    promiseKicker: "My Promise",
    promiseTitle: "Guidance & Approach",
    promiseText: "What sets me apart is my commitment to **ethical guidance** and **personal attention**. I don't believe in generic advice or fear-based predictions. Every consultation and every class is designed to empower you with knowledge, awareness, and practical solutions. I believe that the stars do not dictate your fate — they guide you. And with the right understanding, you can navigate life with confidence and grace.\n\nWhether you are a beginner curious about the stars, a student eager to master the cosmic arts, or someone seeking answers to life's pressing questions — **Arvin Astro** is here for you. My courses are designed for **all levels**, from curious beginners to advanced learners, and my consultation approach is **rooted in classical texts** yet adapted for modern life.\n\nI promise you guidance that is **loyal, precise, and deeply rooted in ethics**. Together, we will gently turn your gaze inward, because the greatest power to change your life resides not in external remedies, but in the sincerity of your own heart and the power of your changing karma.\n\nLet us begin the beautiful work of alignment. Whether it's the stars guiding you, numbers empowering you, or vastu harmonizing your space — **your transformation starts here**.",
    globalTitle: "Global Consultation",
    globalText: "Available for clients in **USA, UK, Canada, and Australia**. Online consultations available worldwide.",
    locationTitle: "Location",
    locationText: "Greater Noida West, UP, India",
    bio: "Welcome to Arvin Astro — your trusted destination for the ancient and life-transforming sciences of Vedic Astrology, Name Numerology, and Vastu Shastra. Whether you are seeking clarity in life, looking for the perfect name for your newborn, or wanting to harmonize your living or working space, you are at the right place.",
    aboutImage: "/images/about.png",
    statYears: "8",
    statStudents: "2666",
    statConsultations: "999",
    whyTitle: "Offering The Best Experience of Cosmic Sciences",
    whyBoxes: JSON.stringify([
      { icon: "sparkle", title: "Deep Vedic Knowledge", desc: "Rooted in classical texts — BPHS, Saravali, Phala Deepika and rare Bhrigu techniques." },
      { icon: "users", title: "Bhrigu Nandi Nadi", desc: "Rare Nadi astrology techniques for precise, life-relevant predictions." },
      { icon: "award", title: "Result-Oriented Remedies", desc: "Simple, logical remedies that do not require heavy structural changes." },
      { icon: "heart", title: "Ethical & Honest Guidance", desc: "I can't change your destiny — but I will guide you there with minimum hurdles, honestly." },
      { icon: "check", title: "Kundli-Aligned Naming", desc: "Names aligned holistically with kundli — an approach very few numerologists practice." },
      { icon: "phone", title: "Global Consultations", desc: "Serving clients in USA, UK, Canada, Australia and beyond, online & offline." },
    ]),
  },
  services: {
    heroTitle: "Expert Astrology, Name Numerology & Vastu Consultation Services",
    heroSubtitle: "Get expert guidance and result-oriented occult science solutions for your life, business, and personal growth. Trusted by clients in India and worldwide.",
    whyTitle: "Astrology Vastu Name Designing for Best Success",
    whyText: [
      "Combining ancient Vedic Wisdom with modern scientific approaches for results that actually work",
      "Vastu is not just about changing furniture — it is about balancing the five elements (Panchbhootas) of your space",
      "Company Name Designing based on numerology and phonetic vibrations for an auspicious start",
      "Newborn Baby Name that is astrologically powerful for the child's future",
      "Logo Designing based on Vastu and color therapy principles so your brand radiates power, trust, and growth",
      "Mobile Number Analysis to help you choose numbers that attract opportunities",
      "Consultation Combos for a holistic approach combining astrology, vastu, and numerology",
    ].join("\n"),
  },
  courses: {
    heroTitle: "A Complete Learning Platform",
    heroSubtitle: "A complete platform for Astrology, Numerology, Name Numerology & Vastu. Learn at your pace, live with the master, or start free.",
  },
  "courses-recorded": {
    heroTitle: "Professional Online Recorded Courses",
    heroSubtitle: "Learn Occult Science at your own pace with our expert-led recorded sessions. Master Astrology, Numerology & Vastu.",
  },
  "courses-free": {
    heroTitle: "Free Online Astrology, Numerology & Vastu Learning Resources",
    heroSubtitle: "Start your occult journey for free! Learn Astrology, Numerology & Vastu with our expert teacher, Arvindrun Vnjay.",
  },
  "courses-live": {
    heroTitle: "Professional Live Numerology, Vastu & Astrology Occult Courses",
    heroSubtitle: "Learn from India's expert Numerologist and Vastu Consultant, Arvindrun Vnjay. Join our online Live classes to master Name Numerology, Predictive Numerology, Astrology and Vastu.",
  },
  books: {
    heroTitle: "Recommended Books for Astrology, Numerology & Vastu Learning",
    heroSubtitle: "We recommend the best astrology, numerology & vastu books for occult science learners — from beginner to advanced level.",
  },
  "vastu-products": {
    heroTitle: "Vastu Products & Energy Remedies",
    heroSubtitle: "Genuine vastu products and spiritual energy remedies for home, office and living spaces — personally recommended by Arvindrun Vnjay.",
  },
  blog: {
    heroTitle: "Insights from the Occult World",
    heroSubtitle: "Practical articles on Astrology, Numerology, Name Numerology and Vastu — written with the learner in mind.",
  },
  footer: {
    copyright: "© 2022-2026 arvinastro.in | All Rights Reserved",
    tagline: "Align Your Karma with Cosmic Energy.",
  },
  notice: {
    noticeEnabled: "false",
    noticeInterval: "4000",
    noticeImage1: "",
    noticeTitle1: "",
    noticeDesc1: "",
    noticeLink1: "",
    noticeImage2: "",
    noticeTitle2: "",
    noticeDesc2: "",
    noticeLink2: "",
    noticeImage3: "",
    noticeTitle3: "",
    noticeDesc3: "",
    noticeLink3: "",
  },
};
